### ISSUE TITLE
final_summary_dataset.R does not produce usable summary data

### ISSUE THREAD

**Issue by dschwilk** [XiulinGao/Grass-Flammability#23]
1. I can't easily figure out what this script dumps into the global namespace. It is undocumented.
2. 'alldata' is a nice data frame but it is not produced by this script but rather by ms-figs.R
3. the PCA data (eg  pcadata.above) has no sample information.  Therefore, I can't line up cpa results with anything useful like species names.  So how can one line up alldata and the pca scores?

For this project, you should have one final full data frame with observations as rows.  Eg "alldata".  If you want to run a pca on a subset, subset it temporarily and then merge the results back in.  As it is I can't figure out how to make figures I really want to make.

**Comment by XiulinGao** [comment]
Also now is fixed on master 04c76bfecf67be39f7f3945b43665fddebefd79f
