### ISSUE TITLE
Find dropped trial or plant id?

### ISSUE THREAD

**Issue by dschwilk** [XiulinGao/Grass-Flammability#24]
https://github.com/XiulinGao/Grass-Flammability/blob/a0b7ed84db668208afcf21b73a1a98a3720a9519/scripts/hobo-temps.R#L75

I can't figure out the aboove statement. Itrial ids have the from date_num, so what is "bi21" A plant id? If something is dropped we must solve that.

**Comment by XiulinGao** [comment]
This is something I forgot to take off when I fixed it, it is the label for the tested plant.
